### PR TITLE
Rework of Stock PRNLs

### PR DESCRIPTION
**Pull request by kbernges**
-Fixes Issue #8
-Adds parts added since 0.90
-Fixes filepaths that have changed since 0.90
-Added new categories for parts that can be reproduced in shape and
function in PP/PWings/PFairings. Parts that do not fit both criteria
(such as radial batteries) are not included in the PRNLs

Update: Added second commit with SXT rework.

### CODE REVIEW

**Comment by kbernges** [comment]
I've since done a rewework of the SXT PRNLs as well, and added that commit.

**Comment by Felger** [comment]
Awesome! I'll have to put together another release of this at some point, there were a couple of merges that changed the script a touch, so I'll need to get that "recompiled" to bundle with it, but thanks for putting these together!

**Comment by kbernges** [comment]
I'll be getting one for VSR that plays nice with SXT done up in the next few days. Won't be as quick as these two since VSR affects stock and (due to the number of stock textures it uses) SXT, and I'm tending towards a more aggressive set of prunelists. The SXT one took a good eight hours due to actually going through all the .cfg files for the mod and making sure the stock textures it uses have an unprune list. I'm going to do the same with VSR.

**Comment by Felger** [comment]
At some point I might just have to query the game database with an in-game plugin to find out what parts use what resources, and auto-build prunelists by checking boxes on a GUI.

**Pull request merged**
